---
title: 我的AI部落格
description: IA、提示語和人機共學共創願景的文獻回顧
author: Hung-Hua Tien
email: bigflowerfrancis@gmail.com

baseurl: "/MyWebsite"  # 若為 GitHub Pages 的 user repo，留空；若是 project repo，要加 /MyWebsite
url: "https://hunghuatien.github.io"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 選填：增加中文支援與 Meta 資訊
lang: zh-TW

---